### ISSUE TITLE
pickleing of Trace objects

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/pyrocko#119]
Why do ```trace.__setstate__``` and ```trace.__getstate__``` ignore the .ydata array and even put it to None?
This prevents a Trace object from being pickleable/forkable etc., because the .ydata will always be None after unpickling.

**Comment by hvasbath** [comment]
any comment @emolch ? In my local fork I just added ydata to the methods and it works perfectly fine. But maybe there is a reason you dont have it there?

**Comment by HerrMuellerluedenscheid** [comment]
This is a good point. Have you tried changin it? Maybe one can quickly run into memory problems? Let's give it a shot and try what happens. If I find the time I'll try next week

**Comment by miili** [comment]
According to @emolch there is an issue w `pile` when `ydata` is pickled... :boom:

**Comment by emolch** [comment]
Yes, we can change this behaviour. The reason why it was implemented like that is because of the pile. This was a simple way to save many traces without data in the pile's metadata file caches. If this is changed in __setstate__ and __getstate__, we also have to update how the metadata caches are created, otherwise all data you ever look at with snuffler will be copied to ~/.pyrocko/...

**Comment by hvasbath** [comment]
Ah ok. Good point. Is just that I am sending traces into the multiprocessing where they are getting pickled/unpickled and then they are empty with the current way of getstate/setstate. Sorry for creating problems ...

**Comment by emolch** [comment]
solved with #131, should I merge and close?

**Comment by hvasbath** [comment]
great!! yes please ;)
