### ISSUE TITLE
avl dependency

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/pyrocko#223]
AVL needs to be in dependency or be optional in code. When installing pyrocko from scratch, opening snuffler will result in error avl module not installed. 
Didnt we fix this already?

**Comment by emolch** [comment]
`pyavl` is required for `pyrocko.pile`, so it is not an optional dependency. It has to be installed with `easy_install` or `pip` for current `master`. In the new `python3-testing` branch, avl is included into pyrocko, because we anyway had to make it work under Python 3, so soon it won't be neccessary to install it separately.

**Comment by braunfuss** [comment]
Under MAC OS easy-install seems to have caused the missing pyavl installation, therefore and because it will be included in the python3 I will close this issue.
