### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tianzeliu** [pyrocko/pyrocko#294]
Hi There,
I was trying to install Pyrocko on my Mac and received the following error message:
`src/ext/signal_ext.c:4:10: fatal error: 'numpy/arrayobject.h' file not found`
Does anyone know what problem it is and how to solve it? Thanks a lot!

Best,
Tianze

**Comment by emolch** [comment]
This means that the NumPy header files are not found when it tries to compile some C functions. This could be caused by different reasons. Either NumPy is not installed, or it is installed without its header files, or it is installed but cannot be found because it has been installed in a different environment. How are you installing the software on your Mac (macports, anaconda, homebrew...?)

**Comment by tianzeliu** [comment]
I installed NumPy using MacPort before installing Pyrocko. However, it seems that it used Python packages installed with Anaconda to install Pyrocko:
`gcc -fno-strict-aliasing -I//anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/include/python2.7 -I -I//anaconda/include/python2.7 -c src/ext/signal_ext.c -o build/temp.macosx-10.6-x86_64-2.7/src/ext/signal_ext.o -Wextra`
which might be part of the cause of the problem.

**Comment by emolch** [comment]
Mixing MacPorts and Anaconda is trouble guaranteed. It is not possible to get a deterministically behaving system with two competing package managers. You would have to set up split environments, one only using Anaconda and one only using MacPorts. If you want to use both.
