### ISSUE TITLE
python setup.py develop

### ISSUE THREAD

**Issue by paugier** [pyrocko/pyrocko#336]
Hi,

The command `python setup.py develop` is very convenient and should work...

The directory src should be named pyrocko...

**Comment by emolch** [comment]
Hi Pierre,

If you need it, you can use
```
sudo rm -rf build pyrocko.egg-info
ln -s src pyrocko
python setup.py develop --user
```
and most things should work. One exception is the import of backward compatibility modules. These are only available after a complete install because they are autogenerated during the build. There were a few imports of these compatibility modules from within pyrocko, these have now been fixed in 021daede2d850aa106765330ebc6efcbb6ae1875.

I personally don't like the develop mode of distutils and prefer to install after every change.

A long time ago, the `src` directory used to be called `pyrocko`. It was renamed on purpose, to prevent accidental import of unfinished changes.

Best wishes
Sebastian

**Comment by paugier** [comment]
Hi Sebastian,

Interesting... Note that naming the package directory in the repository by the name of the package is a **very** standard good practice... Just few examples:

- https://github.com/numpy/numpy
- https://github.com/scipy/scipy
- https://github.com/scikit-learn/scikit-learn
- https://github.com/scikit-image/scikit-image
- https://github.com/pydata/xarray
- https://github.com/numba/numba
- https://github.com/astropy/astropy

When we develop, we want to be sure that we run the tests using the code in the repository! The `ln -s` is a hack. We don't need that.

Anyway, it was just an advice to help.

Let's continue in the same vein... it is not a good idea to install Python packages with `sudo` in the system Python. First, the user needs to be root on the machine and second, OS packages and pip packages do not work well together. Finally, then users have to run commands like `sudo rm -rf ...`, which tends to be dangerous. There shouldn't be `sudo python install` or `sudo pip install` in the documentation... With conda, virtualenv or pyenv, we don't need sudo to work with Python for sciences.

**Comment by emolch** [comment]
Ok, this is a religious issue :-)

In my belief, complexity (https://xkcd.com/1987/) is considered evil and I therefore avoid using conda, virtualenv, etc as far as possible. In my beiief, a system with more than one package manager is doomed. I already have one package manager which comes with my system, so I cannot have any other one. Any additional package I install, I will have to keep track of myself and they should not interfere with my system packages.

Nevertheless, Pyrocko installs nicely with `setup.py --user` or in a conda enviroment, no need to use sudo. However, our install instructions are for a system wide manual default installation which will usually land under `/usr/local/` and does not introduce an extra environment - this is standard in the Unix world.

The change from `pyrocko` to `src` subdirectory for the sources was introduced because the former caused trouble. This convention is used by many other Python packages, like e.g. matplotlib or twisted. I agree that the other is standard but I would not recommend it as good practice because of the accidental import issues.

**Comment by paugier** [comment]
OK. Bye.
