### ISSUE TITLE
conflict with pyqt5, version >= 5.12

### ISSUE THREAD

**Issue by guyomd** [pyrocko/pyrocko#363]
I have just installed pyrocko on a fresh python 3.6 installation.
Snuffler cannot start, i.e. cannot open the GUI and print the following error message:
`
link_to_my_path/bin/python: symbol lookup error: link_to_my_path/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format `

After some investigation online, I suspect an issue with PyQt5 for versions>=5.12.
Indeed, after uninstalling PyQT5 v.5.12, and reinstalling PyQt5 versions 5.11.3 the GUI opened normally at startup !! :-)
(I could also verify that the GUI opened successfully for PyQt5 versions 5.9, and 5.11.2).

Maybe a fix should be planned for the compatibility with PyQT5, v>=5.12 for future updates of Pyrocko.

**Comment by emolch** [comment]
Hi guyomd,

I guess this is a problem with your system (or anaconda?) Qt package. "undefined symbol" errors are due to mismatches in the compiled library dependencies. It is the job of the package manager (or the maintainers providing the compiled packages) to make sure that this does not happen. In the case of anaconda, this is a very fragile thing (if not doomed as a whole :-), because of the many systems anaconda has to run on (this is the competing package manager problem: the system package manager can have N states, anaconda's package manager can have M states, so the system with both together can have NxM states. Complexity is at least proportional to the number of states the system).

At least on my machine (Arch linux, no anaconda, Python 3.7), PyQT 5.12.2 is working fine.

Best regards
Sebastian
